WIP: Apple Watch Talks app
CocoaHeadsConference/CHConferenceApp pull request #45
Opened 2019-10-30 02:25 UTC by leonardorock

Adding a Apple Watch app extension that shows upcoming talk information.

2019-11-04 16:55 UTC, loloop requested changes

2019-11-04 16:55 UTC, loloop commented on NSBrazilConf/Models/TalkModel.swift
> +import Foundation
Esse model não é utilizado no app atual. Cê ainda vai precisar dele?

2019-11-04 16:55 UTC, loloop commented on NSBrazilConfWatchApp WatchKit Extension/Model/Schedule.swift
> +struct Schedule: Codable {
Dessa forma a gente tem que tomar muito cuidado pra não colocar nenhum elemento diferente dentro da lista do schedule, porque o json é compartilhado entre os dois. Não rola usar o `FeedDecoder` pra isso não acontecer?

2019-11-05 01:15 UTC, leonardorock commented on NSBrazilConfWatchApp WatchKit Extension/Model/Schedule.swift
> +struct Schedule: Codable {
Adicionar coisas não é causaria problema, mas sim remover, o motivo de eu não ter usado o FeedDecoder é apenas pra não adicionar todos os models do feed no app do Apple Watch

2019-11-05 01:15 UTC, leonardorock commented on NSBrazilConf/Models/TalkModel.swift
> +import Foundation
Não vou não, pode remover, eu só tinha mudado o import por que não precisava importar o UIKit naquele arquivo

2019-11-06 13:18 UTC, merged